### ISSUE TITLE
Addressing ethereum blockchain size problems from the very beginning

### ISSUE THREAD

**Issue by rogeliotg** [alastria/alastria-platform#4]
Maybe you are aware of ethereum growing problems https://hackernoon.com/the-ethereum-blockchain-size-has-exceeded-1tb-and-yes-its-an-issue-2b650b5f4f62
As seems that you are reusing their technology for alastria blockchain, how do you plan to address these problems? maybe a block size cap? decentralizing nodes?

**Comment by jesus-alastria** [comment]
This is a VERY important question and one that is not easy to solve. The article that you reference is a very good one.
However, we think the solution for Alastria lies in the fact that it is a Public-Permissioned network, in contrast to Public-Permissionless networks like Bitcoin or Ethereum.
This problem is incredibly hard to solve in a permissionless network, but not so much in a permissioned one.
Being public-permissioned, Alastria is less decentralized than Ethereum, but much more decentralized than private consortiums.
The participants in Alastria do not have to trust on anonymous actors, but they already have to trust that thanks to the IBFT, a reduced set of well-known Validators perfrorm COLECTIVELLY their duties and the network is secure. Participants do NOT HAVE to trust on each individual validator node, instead they have to trust that they are not going to COLLUDE among them to affect that participant. The safety of the network depends on choosing the validators so they will not collude. But this is another VERY important topic related not just to technology but to Governance.
Coming back to the size of the blockchain: if a participant does NOT TRUST any other node in Alastria, there is at this moment no other solution than maintaining the full blockchain history.
But is a participant is willing to trust "a littlke bit" on other well-known nodes (not necessarily individual nodes), then those other nodes (bigger and more powerful), could implement "collective checpointing" that other nodes could use. The objective is to facilitate to participants (if the wish) the ability to maintain themselves just enough recent history for their needs (6 months, 1 year, 3 years, ...)
The mechanism would allow for checking the checkpoints against more than a single node, to decrease the probability that the trusted node could "manipulate" those checkpoints.
The technical mechanisms, coupled with full publicity of the node's identity and checkpoint status, could provide what we think is a very good level of trust to be of practical use in Alastria.

Anyway, if you are interested in this, you are more than welcome to collaborate on thsi very important subject. We need help from everybody that shares the vison of Alastria.
